/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;


/**
 *
 * @author andrik y julio
 */
public class GUI_imprimir extends javax.swing.JFrame {

   
    Agenda agenda;

    public static String nombreEntrada;

    public GUI_imprimir(Agenda agenda2) {
        initComponents();
        this.agenda = agenda2;
        this.jCorreo.setVisible(false);
        this.tf_correo.setVisible(false);
        this.jApodo.setVisible(false);
        this.tf_apodo.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        tf_nombre_a_buscar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        tf_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_primer_apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_segundo_apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_cedula = new javax.swing.JTextField();
        tf_sexo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_edad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_telefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_correo = new javax.swing.JTextField();
        jCorreo = new javax.swing.JLabel();
        tf_apodo = new javax.swing.JTextField();
        jApodo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("IMPRIMIR DATOS ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 330, 80));

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 90, -1));
        jPanel1.add(tf_nombre_a_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 130, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 670, 20));
        jPanel1.add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 150, -1));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 110, 20));

        jLabel3.setText("Primer Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 110, 20));
        jPanel1.add(tf_primer_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 150, -1));

        jLabel4.setText("Segundo Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 110, 20));
        jPanel1.add(tf_segundo_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 150, -1));

        jLabel5.setText("Cedula:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 340, 100, 20));
        jPanel1.add(tf_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 150, -1));
        jPanel1.add(tf_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 150, -1));

        jLabel6.setText("Sexo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 100, 20));
        jPanel1.add(tf_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 150, -1));

        jLabel7.setText("Edad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 40, 20));
        jPanel1.add(tf_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 150, -1));

        jLabel8.setText("Telefono:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 50, 20));
        jPanel1.add(tf_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 150, -1));

        jCorreo.setText("Correo:");
        jPanel1.add(jCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 340, 50, 20));
        jPanel1.add(tf_apodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 150, -1));

        jApodo.setText("Apodo:");
        jPanel1.add(jApodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 300, 50, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        tf_correo.setVisible(false);
        jCorreo.setVisible(false);
        tf_apodo.setVisible(false);
        jApodo.setVisible(false);
        
        nombreEntrada = tf_nombre_a_buscar.getText();
        Contacto contacto = agenda.obtenerContacto(nombreEntrada);
        
        tf_nombre.setText(contacto.getPersona().getNombre());
        tf_primer_apellido.setText(contacto.getPersona().getPrimerApellido());
        tf_segundo_apellido.setText(contacto.getPersona().getSegundoApellido());
        tf_edad.setText(Integer.toString(contacto.getPersona().getEdad()));
        tf_sexo.setText(Character.toString(contacto.getPersona().getSexo()));
        tf_cedula.setText(contacto.getPersona().getCedula());
        tf_telefono.setText(Integer.toString(contacto.getTelefono()));
        
        if (contacto.getClass() == ContactoT1.class ) {
            
            tf_correo.setVisible(true);
            jCorreo.setVisible(true);
            
            tf_correo.setText(contacto.getAtributoExtra());
             
        } else {
            tf_apodo.setVisible(true);
            jApodo.setVisible(true);
            tf_apodo.setText(contacto.getAtributoExtra());
            
        }
        
    }//GEN-LAST:event_btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_imprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_imprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_imprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_imprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new GUI_imprimir().setVisible(true);
////            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JLabel jApodo;
    private javax.swing.JLabel jCorreo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField tf_apodo;
    private javax.swing.JTextField tf_cedula;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_nombre;
    public javax.swing.JTextField tf_nombre_a_buscar;
    private javax.swing.JTextField tf_primer_apellido;
    private javax.swing.JTextField tf_segundo_apellido;
    private javax.swing.JTextField tf_sexo;
    private javax.swing.JTextField tf_telefono;
    // End of variables declaration//GEN-END:variables
}
